### ISSUE TITLE
v6.13?

### ISSUE THREAD

**Issue by Sameow** [openmusic-project/OM6#10]
Hi, may I know where to download v6.13? I noticed that it is missing in https://github.com/openmusic-project/OM6/releases 

If someone created patches using v6.13, would I be able to use it correctly in the latest release?

**Comment by j-bresson** [comment]
Hi !
1) You can find OM releases from 6.5 to 6.14 on this "Archive" page from IRCAM: http://forumnet.ircam.fr/shop/fr/archived.php?id_product=43&archived=1

2) Yes, a patch created in OM 6.13 should open without problem in OM 6.15

3) Please post questions / issues on the OpenMusic discussion group, recently relocated here : https://discussion.forum.ircam.fr/c/openmusic

Best,
