### ISSUE TITLE
Exporting MIDI pitch-bends in SAVE-AS-MIDI

### ISSUE THREAD

**Issue by j-bresson** [openmusic-project/OM6#14]
The attached patch doesn't seen to export very well with SAVE-AS-MIDI
Approx 8 / Retune-channels ON
The MIDIFile box sounds 1 tone too low: there's a wrong interpretation or encoding of the PïtchBend event somewhere.
When open in a DAW (Garage Band), the PitchBends seem just ignored.

<img width="803" alt="Capture d’écran 2019-10-27 à 09 34 57" src="https://user-images.githubusercontent.com/7666142/67631990-bf076e80-f89d-11e9-864d-8b4a4920f236.png">

**Comment by andersvi** [comment]
The resulting midi-file plays ok here using an external midi-player (timidity), and when dumping the data: 
`[andersvi@josefk out-files]$ midicsv test.mid 
0, 0, Header, 1, 2, 1000
1, 0, Start_track
1, 0, Pitch_bend_c, 0, 8192
1, 0, Pitch_bend_c, 1, 9216
1, 0, Pitch_bend_c, 2, 10240
1, 0, Pitch_bend_c, 3, 11264
1, 0, Tempo, 1000000
1, 0, End_track
2, 0, Start_track
2, 0, Note_on_c, 0, 60, 100
2, 998, Note_off_c, 0, 60, 0
2, 1000, Note_on_c, 1, 60, 100
2, 1998, Note_off_c, 1, 60, 0
2, 2000, Note_on_c, 2, 60, 100
2, 2998, Note_off_c, 2, 60, 0
2, 3000, Note_on_c, 3, 60, 100
2, 3998, Note_off_c, 3, 60, 0
2, 3998, End_track
0, 0, End_of_file
[andersvi@josefk out-files]$ `

**Comment by andersvi** [comment]
But i observe the same behavior on playback.  

If just playing the chord-seq initially, it starts on the expected note, and jumps up a semitone on 6050.  

If evaluating the save-as-midi first, everything jumps down a major second, and stays there, until i do `(microplay-reset 0 :portmidi)`

**Comment by andersvi** [comment]
Do some of these byte-packages for note-on/off look a bit strange?

**Comment by andersvi** [comment]
If the ev-fields of the :PitchBend event is a list isn't interpreted as it should. If instead the ev-fields is an integer it plays ok.  I'll have a look somewhere in #'make-midi-bytes in portmidi-api.lisp ...
